apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podimportances.example.com  # Make sure to include the group name
spec:
  group: example.com
  names:
    kind: PodImportance
    plural: podimportances
    singular: podimportance
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                purpose:
                  type: string
                  description: "How important is this? This helps when you have more than 2 layers of importance, so that other team members don't misuse and place the appropriate importance level. For example, importance level 4 (e.g., highest) description will be: use only."
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                      description: "Labels to select the pods for assigning importance."
                importanceLevel:
                  type: integer
                  description: "The importance level assigned to the selected pods. Higher number means higher importance."
              required:
                - selector
                - importanceLevel
