apiVersion: core.192.168.49.2/v1
kind: MemoryKeeper
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: memorykeeper-sample
spec:
  # TODO(user): Add fields here
