# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-service-account-token
  namespace: testing-rbac-1
  annotations:
    kubernetes.io/service-account.name: my-service-account
type: kubernetes.io/service-account-token