# Dockerfile.base
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb files to install dependencies
COPY ./package.json ./bun.lockb* ./

# Install dependencies
RUN bun install

# Expose a port if your app requires it
EXPOSE 3000

# This base image will not have a CMD or ENTRYPOINT yet

