# permissions for end users to edit importancelevels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: memmory-keeper
    app.kubernetes.io/managed-by: kustomize
  name: importancelevel-editor-role
rules:
- apiGroups:
  - custom.my.domain
  resources:
  - importancelevels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.my.domain
  resources:
  - importancelevels/status
  verbs:
  - get
