apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-external
  template:
    metadata:
      labels:
        app: postgres-external
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "youruser"
        - name: POSTGRES_PASSWORD
          value: "yourpassword"
        - name: POSTGRES_DB
          value: "yourdb"
