# permissions for end users to view memorykeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: memorykeeper-viewer-role
rules:
- apiGroups:
  - core.192.168.49.2
  resources:
  - memorykeepers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.192.168.49.2
  resources:
  - memorykeepers/status
  verbs:
  - get
