[package]
name = "customsandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
nix =  {version = "0.29", features = ["ptrace"]}
regex = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"